### PR TITLE
Fix #22?

### LINKED ISSUE #22: Output correctly formatted C
For example, `examples/factorial.hau` compiles to..

```c
long factorial(long n) {

    {
        if  (n == 0l)             return 1l;        else             return (n * factorial((n - 1l)));
    }

    return 0l;
}

int main() {

    {
        display(factorial(5l));

    }

    return 0l;
}
```

### PR DESCRIPTION
**Pull request by Jonathan50**
Now the factorial example compiles to
```c
long factorial(long n) {
    {
        if (n == 0l)
            return 1l;
        else
            return (n * factorial((n - 1l)));
    }
    return 0l;
}

int main() {
    {
        display(factorial(5l));
    }
    return 0l;
}
```

### CODE REVIEW

**Comment by nanalan** [comment]
Looks like the `if` outputs one too many spaces, still.

```
if  (n == 0l) 
  ^^
```

**Comment by Jonathan50** [comment]
Oh, I didn't notice that.

**Comment by Jonathan50** [comment]
Note: with this then blocks in if/while/for statements aren't special cases, so
```haumea
to main do
  if 1 = 1 then do        
    display(1) display(2)
  end
end
```
compiles to
```c
int main() {
    {
        if (1l == 1l)
            {
                display(1l);
                display(2l);
            }
    }
    return 0l;
}
```
This makes sense to me, but many C programmers hate this style&hellip; Should it change?

**Comment by nanalan** [comment]
> ..many C programmers hate this style..

Yeah, probably best to use 1TBS, if possible... the best result would be not generating `do .. end` braces when they aren't needed:

```c
int main()
{
    if (1l == 1l) {
        display(1l);
        display(2l);
    }
    return 0l;
}
```

**Comment by Jonathan50** [comment]
Okay, so have a procedure called `compile_statement_wo_extra_braces` or something and have the code generators for `if`, `forever`, `while` and `for each` output braces call it instead of `compile_statement`?

**Pull request merged**
